[package]
name = "os-terminal"
version = "0.3.6"
edition = "2021"
authors = ["Xuanjun Wen <wenxuanjun@yahoo.com>"]
description = "Beautiful terminal emulator on no-std environment"
keywords = ["terminal", "console", "os", "no-std"]
categories = ["embedded", "gui", "no-std"]
license = "MIT"
homepage = "https://github.com/wenxuanjun/os-terminal"
repository = "https://github.com/wenxuanjun/os-terminal"
exclude = ["screenshot.png"]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1

[dependencies]
vte = "0.13.0"
bitflags = "2.6.0"
spin = "0.9.8"

[dependencies.ab_glyph]
version = "0.2.28"
features = ["libm", "variable-fonts"]
optional = true
default-features = false

[dependencies.noto-sans-mono-bitmap]
version = "0.3.0"
features = [
    "regular",
    "bold",
    "size_20",
    "unicode-basic-latin",
    "unicode-specials",
]
optional = true
default-features = false

[dev-dependencies]
minifb = "0.27.0"
crossbeam-channel = "0.5.13"

[dev-dependencies.nix]
version = "0.29.0"
features = ["term", "process", "fs"]

[features]
default = ["bitmap"]
bitmap = ["dep:noto-sans-mono-bitmap"]
truetype = ["dep:ab_glyph"]

