[package]
name = "os-terminal"
version = "0.4.4"
edition = "2021"
authors = ["Xuanjun Wen <wenxuanjun@yahoo.com>"]
description = "Beautiful terminal emulator on no-std environment"
keywords = ["terminal", "console", "os", "no-std"]
categories = ["embedded", "gui", "no-std"]
license = "MIT"
homepage = "https://github.com/wenxuanjun/os-terminal"
repository = "https://github.com/wenxuanjun/os-terminal"
exclude = ["/examples", "screenshot.png"]

[[example]]
name = "terminal"
required-features = ["truetype"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
vte = "0.13.0"
bitflags = "2.6.0"
spin = "0.9.8"
pc-keyboard = "0.8.0"
unicode-width = "0.2.0"

[dependencies.ab_glyph]
version = "0.2.29"
features = ["libm", "variable-fonts"]
optional = true
default-features = false

[dependencies.noto-sans-mono-bitmap]
version = "0.3.0"
features = [
    "regular",
    "bold",
    "size_20",
    "unicode-basic-latin",
    "unicode-specials",
]
optional = true
default-features = false

[dev-dependencies]
crossbeam-channel = "0.5.13"
keycode = "0.4.0"

[dev-dependencies.nix]
version = "0.29.0"
features = ["term", "process", "fs"]

[dev-dependencies.winit]
version = "0.30.5"
features = ["rwh_06", "x11", "wayland"]
default-features = false

[dev-dependencies.softbuffer]
version = "0.4.6"
features = ["kms", "x11", "wayland"]
default-features = false

[features]
default = ["bitmap"]
bitmap = ["dep:noto-sans-mono-bitmap"]
truetype = ["dep:ab_glyph"]
